# Generated by Django 2.2.4 on 2019-09-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexp',
            name='end',
            field=models.DateField(blank=True),
        ),
    ]
