# Generated by Django 2.2.4 on 2019-09-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myprofile', '0002_auto_20190914_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexp',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
