# Generated by Django 2.2.4 on 2019-09-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showresume',
            name='res',
            field=models.FileField(upload_to='images/'),
        ),
    ]
